@startuml out
allowmixing

class String

class  Int

actor User

component PCM_DC{
    port BR1
    port  BR2
    port  BR3
}

component PCM_DC_Base
component Suitability
component DWH{
    port 2
}

Suitability <--> PCM_DC

BR1 --> 2

interface Integrable

class Integrator
@enduml
