@startuml sample
allowmixing

actor Client 

actor RelationshipManager 

component RESTService  {
    port 443
}

package Retail.CRM { 
component CustomerDB <<GDPR>> {
    port 443
    port REST
}
 
}
package Retail { 
component CustomerSearch  {
    port 443
}
 
}
443 ..> REST

@enduml
