name: PR - Build / Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.40.3
          cache: true

      - name: Test
        run: pixi run test

      - name: Docs
        run: pixi run doc

      - name: "Coverage report artifact"
        uses: actions/upload-artifact@v4
        with: 
          name: code-coverage-report
          path: test-results/coverage/html
        if: ${{ always() }}
      - name: "Documentation artifact"
        uses: actions/upload-artifact@v4
        with: 
          name: docs
          path: docs/build/html
